# Generated by Django 4.2.7 on 2024-11-17 11:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                ("ques_id", models.AutoField(primary_key=True, serialize=False)),
                ("ques_number", models.PositiveIntegerField(unique=True)),
                ("ques_title", models.TextField()),
                ("ques_detail", models.TextField()),
                ("ques_option", models.JSONField()),
                ("ques_answer", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user_name",
                    models.CharField(
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Username can only contain letters, numbers, underscores, and dots.",
                                regex="^[a-zA-Z0-9_.]+$",
                            )
                        ],
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.PositiveIntegerField()),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "ques_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.questions"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.users"
                    ),
                ),
            ],
        ),
    ]
