# Generated by Django 4.2.7 on 2024-11-18 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0002_questions_ques_category_questions_ques_difficulty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="history",
            old_name="answer",
            new_name="user_answer",
        ),
    ]
